#!/usr/bin/perl
# this script plots all but the first column of a file against the first
if ( $#ARGV == 0 )
{ $how = "w l"; }
elsif ( $#ARGV == 1 )
{ $how = $ARGV[ 1 ]; }
else
{ die "usage: $0 filename 'how to plot'\n\n"; }
$infile=$ARGV[0];
($outfile=$infile)=~s/.out$/.gp/;
($epsfile=$infile)=~s/.out$/.eps/;
print "from $infile to $outfile (creates $epsfile)\n";
$line = `head -1 $infile`;
@cols = split(/\s+/,$line);
# $#cols is # of cols - 1

#finish this later
open GP, ">$outfile" || die "couldn't open $outfile";
#print GP "set nokey\n";
print GP "set term postscript eps color solid\n";
print GP "set output '$epsfile'\n";
#my $title = $ARGV[ 3 ] . " varying";
#my $title = $infile . ", " . $ARGV[ 1 ] . " varying";
my $title = $infile;
print GP "set title \"$title\"\n";
print GP "plot";
for( $i = 0; $i < $#cols + 0; ++$i ) {
  if( $i > 0 ) {
    print GP ",";
  }
  print GP " '$infile' using 1:",$i+2," title \"$i\" $how";
}
print GP "\n";
close GP;
