#!/usr/bin/perl
# special script for plotting fft with X's
# usage:
#  plot-fft fftfile eigenvalue-magphase-file {-d|-bw|-g gpfile|-e epsfile}
my $infile, $eigenfile, $gpfile, $epsfile;
my $dbg = 0;
my $color = 1;
while (@ARGV)
{
  my $arg = shift ARGV;
  if ($arg =~ /^-d$/)
  { $dbg = 1;
    $dbg && print "saw -d option\n";
  }
  elsif ($arg =~ /^-bw$/)
  { $color = 0;
    $dbg && print "saw -bw option\n";
  }
  elsif ($arg =~ /^-g$/)
  { $gpfile = shift ARGV;
    $dbg && print "saw -g $gpfile option\n";
  }
  elsif ($arg =~ /^-e$/)
  { $epsfile = shift ARGV;
    $dbg && print "saw -e $epsfile option\n";
  }
  else
  { $dbg && print "regular argument $arg\n";
    $infile = $arg;
  }
#  else
#  { die "usage: $0 filename\n\n"; }
}
if (!defined $gpfile)
{ ($gpfile=$infile)=~s/.out$/.gp/; }
if (!defined $epsfile)
{ ($epsfile=$gpfile)=~s/.gp$/.eps/; }
print "from $infile, $eigenfile to $gpfile (creates $epsfile)\n";
my $T = `wc -l $infile`;
open GP, ">$gpfile" || die "couldn't open $gpfile";
#print GP "set nokey\n";
print GP "set term postscript eps".($color?" color":"")." solid\n";
print GP "set output '$epsfile'\n";
#my $title = $infile;
#print GP "set title \"$title\"\n";
print GP "plot";
for( $i = 0; $i <= $#ycols; ++$i ) {
  if( $i > 0 ) {
    print GP ",";
  }
  print GP " '$infile' using $xcol:$ycols[$i] title \"$ycols[$i]\" $with";
}
print GP "\n";
close GP;
