#!/usr/bin/perl
# this script plots age distribution into a file
my $infile=$ARGV[0];
my $outfile; ($outfile=$infile) =~ s/.out/.gp/;
my $epsfile; ($epsfile=$infile) =~ s/.out/.eps/;
print "from $infile to $outfile\n";
my $n;
die 'No n' unless (($outfile=~/n.(\d+)./) && ($n = $1));
open GP, ">$outfile";
print GP "set nokey\n";
print GP "set term postscript eps color solid\n";
print GP "set output '$epsfile'\n";
print GP "#set pointsize 0.1\n";
print GP "plot ";
print GP "[0:200] '$infile' using 0:1 title 'y[0]' w lp 1";
#foreach $i (1 .. $n) 
#{ if ($i > 1) { print GP ','; }
#  print GP " '$infile' using 0:".($i)." title 'y[$i]' w l $i";
#}
print GP "\n";
close GP;
