#!/usr/bin/perl
# this script makes a .gp that plots the first column of .out into .eps
my $infile=shift @ARGV;
my $color = 1;
while ($arg = shift @ARGV)
{ if ($arg=~/^-bw$/)
  { $color = 0; print "saw $arg option\n"; }
}
my $dataname; ($infile=~/\.([^\.]+)\.out/)&&($dataname=$1);
my $outfile; ($outfile=$infile) =~ s/\.out/.gp/;
#if ($dataname == "x") { $outfile =~ s/x\./x0./; }
my $epsfile; ($epsfile=$outfile) =~ s/\.gp/.eps/;
print "from $infile to $outfile (makes $epsfile)\n";
#my $n;
#die 'No n' unless (($outfile=~/n.(\d+)./) && ($n = $1));
open GP, ">$outfile";
print GP "set nokey\n";
print GP "set term postscript eps ",($color?"color solid":""),"\n";
print GP "set output '$epsfile'\n";
print GP "#set pointsize 0.1\n";
print GP "plot ";
print GP "[0:*] '$infile' using 0:1 title 'x[0]' w lp 1";
#foreach $i (1 .. $n) 
#{ if ($i > 1) { print GP ','; }
#  print GP " '$infile' using 0:".($i)." title 'x[$i]' w l $i";
#}
print GP "\n";
close GP;
